### ISSUE TITLE
Realtime Database rules

### ISSUE THREAD

**Issue by SwissCheese5** [anboralabs/intellij-firebase-highlighter#107]
**Is your feature request related to a problem? Please describe.**
No Firebase Realtime Database support.

**Describe the solution you'd like**
Firebase Realtime Database support. Should activate with files `database.rules.json`

**Describe alternatives you've considered**
Fireabse Realtime Database security rules web UI.

**Comment by dalgarins** [comment]
Issue cloned to https://github.com/anboralabs/intellij-firebase/issues/7

**Comment by dalgarins** [comment]
<img width="923" alt="Captura de Pantalla 2022-09-19 a la(s) 9 07 19 a m" src="https://user-images.githubusercontent.com/8527174/191036952-5566d4cc-88e3-4f6c-9997-880866cdc79a.png">

@SwissCheese5 Added support to realtime db rules, will be available soon, I'm still testing, if you have a custom file rule to share add on issue to test the plugin.

**Comment by dalgarins** [comment]
the feature will available on version: 2022.5.1

**Comment by SwissCheese5** [comment]
Hey, not in a position to test. Thank you so much though! I appreciate it.
