### ISSUE TITLE
Invalid syntax for firestore methods in storage.rules

### ISSUE THREAD

**Issue by dbc-dev** [anboralabs/intellij-firebase-highlighter#109]
**Describe the bug**
`firestore.get()` and `firestore.exists()` methods inside **storage.rules** are not properly handled resulting in false syntax errors.

**To Reproduce**
In the storage.rules file add either of the methods above using the examples provided in the [documentation](https://firebase.google.com/docs/storage/security/rules-conditions#enhance_with_firestore).

**Expected behavior**
No errors.

**Screenshots**
<img width="708" alt="Captura de ecrã 2022-12-27, às 01 11 29" src="https://user-images.githubusercontent.com/75276387/209595889-de4c7b2f-a88b-442a-a888-0416196c9f13.png">

<img width="373" alt="Captura de ecrã 2022-12-27, às 01 09 25" src="https://user-images.githubusercontent.com/75276387/209595783-d3f51e3f-39f1-4143-9d7e-d61fedcf172f.png">

**Desktop:**
 - OS: macOS
 - IDE: IntelliJ IDEA 2022.3.1 (Ultimate Edition) (17.0.5+1-b653.23 aarch64)
 - Plugin Version: 2022.5.4

**Comment by dalgarins** [comment]
Issue cloned to https://github.com/anboralabs/intellij-firebase/issues/18

**Comment by dalgarins** [comment]
Hi @dbc-dev the issue will be fixed on version: 2022.6.0

<img width="840" alt="Captura de Pantalla 2022-12-27 a la(s) 5 45 08 p m" src="https://user-images.githubusercontent.com/8527174/209731627-51062730-3473-4fc5-91c1-a8a4088c74df.png">
