### ISSUE TITLE
erroneous errors about path substitutions

### ISSUE THREAD

**Issue by stevethehu** [anboralabs/intellij-firebase-highlighter#111]
**Describe the bug**
Path in a rule compiles and works fine, but the plugin treats it as an error.

**To Reproduce**
1. create a rule with a line like:
`              && exists(/databases/$(database)/documents/Dxxxxs/$(userId)/FxxxxxRxxxxxxx/$(xxxxxFxxxxxxxx()[0])))`
2. trigger code analysis (I'm using Android Studio)
3. See errors:
```
    Error:(77, 25) ')', '/', <expression> or null expected, got '/'
    Error:(77, 36) '.', <expression>, IDENTIFIER or PATH_BUILT_IN_LITERAL expected, got '$(database)'
```

**Expected behavior**
This compiles fine according to the Firestore Rules engine, but the plugin shows these errors. I think the syntax matches what's documented [here](https://firebase.google.com/docs/firestore/security/rules-conditions#access_other_documents).

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Android Studio Dolphin | 2021.3.1 Patch 1
 - Version: 2023.1.2 (plugin version)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dalgarins** [comment]
Issue cloned to https://github.com/anboralabs/intellij-firebase/issues/39

**Comment by stevethehu** [comment]
> Issue cloned to https://github.com/anboralabs/intellij-firebase/issues/39

That link gives me a 404. Same for the others on the other issues I just created.

**Comment by dalgarins** [comment]
Hi @stevethehu the issue is fixed: it will available on version: 2023.1.5

<img width="1145" alt="Captura de Pantalla 2023-01-25 a la(s) 7 09 34 p m" src="https://user-images.githubusercontent.com/8527174/214722531-5631719c-7c5c-4bad-a045-74ea8e5cd844.png">

**Comment by stevethehu** [comment]
thank you for the speedy response and turnaround, @dalgarins ! I'm looking forward to the new version update

**Comment by dalgarins** [comment]
@stevethehu the new version in available on marketplace, let me know if the issue is fixed to you.
