### ISSUE TITLE
Error about any signed-in account should be a warning

### ISSUE THREAD

**Issue by stevethehu** [anboralabs/intellij-firebase-highlighter#112]
**Describe the bug**
I have some documents that I would like any signed-in user to be able to access, but the plugin is treating this as an error.

**To Reproduce**
1. implement rule allowing some operation if only `request.auth != null`
2. trigger rules analysis (I'm using Android Studio)
3. See error:
`Error:(34, 22) 'allow read' rule inside 'match /Doc/{docId}'checks for 'request.auth != null', which allows any signed in account (including anonymous accounts if enabled in Firebase Auth) to access data`

**Expected behavior**
I think it could be reasonable to make this a warning, but even then I'd want to disable it. I think allowing access to any signed-in user can be reasonable (though I'm new to Firestore, so maybe I'm misunderstanding what I'm actually doing). Even if it's a warning, I'd want to be able to disable it instead of it popping up when I want to commit a change as something I need to then review and click again to commit ignoring warnings.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Editor: Android Studio Dolphin | 2021.3.1 Patch 1
 - Version: 2023.1.2

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dalgarins** [comment]
Issue cloned to https://github.com/anboralabs/intellij-firebase/issues/40

**Comment by dalgarins** [comment]
Hi @stevethehu can you add a screenshot for this part: **Even if it's a warning, I'd want to be able to disable it instead of it popping up when I want to commit a change as something I need to then review and click again to commit ignoring warnings.**

**Comment by stevethehu** [comment]
<img width="293" alt="Screenshot 2023-01-25 at 1 27 17 PM" src="https://user-images.githubusercontent.com/105839077/214695091-acd43ab6-ced7-49af-9d6b-d0cd446325ee.png">

is this what you're looking for? if I press Commit or Commit and Push..., the buttons will turn into Commit Anyway, or Commit Anyway and Push... for 10 seconds or so. I don't want to have to ignore these spurious errors because they could cause me to miss real errors

**Comment by dalgarins** [comment]
You can disable the firebase linter of my plugin to avoid the issue marks.

<img width="979" alt="Captura de Pantalla 2023-01-25 a la(s) 7 12 50 p m" src="https://user-images.githubusercontent.com/8527174/214723192-2c9d6a8e-db92-4426-8dc3-9c0a4d428e35.png">

let me know if this solution fit to you.

**Comment by stevethehu** [comment]
are all of the settings under Firebase provided by your plugin? I would expect the "allow any signed in account" to match the "Weak rules" linter setting, but that was already disabled by default in my IDE

**Comment by dalgarins** [comment]
Yes, all options under firebase are from my plugin, weak rules are disable by default. I'm going to be working to give the users the option to change the type of message warning or error.

@stevethehu also if you consider to change the starts in your comment in the intellij marketplace, it could be great. that help me.

**Comment by stevethehu** [comment]
@dalgarins I'm happy to upgrade my review given your support and quick responses, but I don't see a way to edit it. should I delete it and create a new review, or am I missing something (this is my first IntelliJ marketplace purchase)?

**Comment by dalgarins** [comment]
@stevethehu I was looking for an edit button, but I wasn't able to find it, I guess you have to delete the comment, but to be fair, copy your first comment delete it and in the new comment paste the previous comment and add an update note; saying that you update your comments and the reasons.

**Comment by dalgarins** [comment]
@stevethehu I think this issue is solved, I'm going to close it, if you have any other comments open again.
