### ISSUE TITLE
Install fails when using Android Studio Dolphin

### ISSUE THREAD

**Issue by LP0815** [anboralabs/intellij-firebase-highlighter#114]
When trying to install the dowloaded jar file I am getting the error:

Plugin 'Firebase Rules Syntax Highlighter' (version '1.0-SNAPSHOT') is not compatible with the current version of the IDE, because it requires build 202.* or older but the current build is AI-213.7172.25

Is there I way to install it anyway or is it really incompatible?

**Comment by dalgarins** [comment]
Issue cloned to https://github.com/anboralabs/intellij-firebase/issues/54

**Comment by dalgarins** [comment]
@LP0815  the latest version for AI-213.7172.25 is: 2023.2.2 (paid version)
but if you want a free version you can install: 2.7.0 the only complaint about that you won't have the latest code, that includes, a linter for firebase rules and some issues fixed.
