### ISSUE TITLE
Bug: plugin incorrect requires semicolons

### ISSUE THREAD

**Issue by webbertakken** [anboralabs/intellij-firebase-highlighter#115]
Consider the following correct syntax of firebase storage rules:

![image](https://user-images.githubusercontent.com/20756439/235252770-bca2232d-c50a-4fe1-89e2-5e08003b3fff.png)

The plugin marks it as incorrect because it's picky about having semicolons.

![image](https://user-images.githubusercontent.com/20756439/235252940-17aaedf6-66ad-49cb-a4d8-99ee0a867ae6.png)

How to reproduce:

Open the editor on Windows 11, WebStorm 2023.1, Plugin 2023.4.1 and paste the following in a file called `storage.rules`.

```json5
rules_version = '2';
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write: if false
    }

    match /users/{userId}/songs/{songId}/parts/{partId} {
      allow read: if userId == request.auth.uid
      allow write: if userId == request.auth.uid
        && request.resource.size < 8 * 1024 * 1024
        && request.resource.contentType.matches('audio/.*')
    }
  }
}
```

**Comment by dalgarins** [comment]
<img width="1012" alt="Screenshot 2023-04-28 at 5 47 20 PM" src="https://user-images.githubusercontent.com/8527174/235266031-fa5f5519-6c88-49cb-93cf-d805ff05ec53.png">

thanks the fix will be available on next version: 2023.4.3

**Comment by dalgarins** [comment]
@webbertakken the update is available.

**Comment by webbertakken** [comment]
Thank you very much! Will test it ASAP.

**Comment by webbertakken** [comment]
I can confirm that this now works as expected.
