### ISSUE TITLE
Subfield indexing

### ISSUE THREAD

**Issue by emiliodallatorre** [anboralabs/intellij-firebase-highlighter#118]
At the moment, this plugin is highlighting as an error the indexes working on subfields.
For instance, the following is highlighted as an error.
```
            {
                "fieldPath": "geoPoint.geohash",
                "order": "ASCENDING"
            }
``` 

I think this should be fixed by admitting dots into the fieldPath value.

**Comment by dalgarins** [comment]
Issue cloned to https://github.com/anboralabs/intellij-firebase/issues/71

**Comment by dalgarins** [comment]
@emiliodallatorre which version of the plugin do you have installed?

**Comment by dalgarins** [comment]
<img width="1015" alt="Screenshot 2023-11-03 at 7 58 30 AM" src="https://github.com/anboralabs/intellij-firebase-highlighter/assets/8527174/22399e75-c936-45b0-b476-465115d70428">

@emiliodallatorre issue was fixed and will be available on next release.

**Comment by emiliodallatorre** [comment]
> <img alt="Screenshot 2023-11-03 at 7 58 30 AM" width="1015" src="https://user-images.githubusercontent.com/8527174/280285453-22399e75-c936-45b0-b476-465115d70428.png">
> @emiliodallatorre issue was fixed and will be available on next release.

Glad to hear that!
Thank you so much!
