### ISSUE TITLE
Not compatible with the current version of the IDE

### ISSUE THREAD

**Issue by CTOverton** [anboralabs/intellij-firebase-highlighter#119]
**Describe the bug**

> Plugin 'Firebase Rules Syntax Highlighter' (version '1.0-SNAPSHOT') is not compatible with the current version of the IDE, because it requires build 202.* or older but the current build is WS-241.15989.105

**To Reproduce**
1. Using Webstorm v 241
```
- Go to https://github.com/anboralabs/intellij-firebase-highlighter/releases/tag/v1.0.0
- download firebase-syntax-highlighting-1.0-SNAPSHOT.jar
- Plugins -> Install From disk -> choose the file downloaded
```

**Expected behavior**
Plugin should work

**Screenshots**
<img width="426" alt="image" src="https://github.com/anboralabs/intellij-firebase-highlighter/assets/33900517/2e7048a0-16ec-4342-b7c0-a1ccd92ac533">

**Desktop:**
 - OS: MacOS

**Comment by dalgarins** [comment]
Issue cloned to https://github.com/anboralabs/intellij-firebase/issues/78

**Comment by dalgarins** [comment]
That version is incompatible with your IDE version. That's the meaning of the notification that you IDE shows. Try with latest versions.

**Comment by CTOverton** [comment]
@dalgarins I understand that, I tried cloning from the latest version of this repo as well and faced the same issue. Is this plugin not supported for v241 yet?

**Comment by dalgarins** [comment]
It's supported open plugins marketplace in your IDE and search firebase, and you will see the plugin available.

**Comment by CTOverton** [comment]
@dalgarins the only option I see there is the paid version, is there no free tier?

**Comment by dalgarins** [comment]
@CTOverton there is a free trial version from marketplace, 30 days to test the plugin, maintain the plugin and update with each version it's a hard work, that's the reason for annual payment, you can download the code compile and make it compatible with your IDE version.
