### ISSUE TITLE
False positive in helper function

### ISSUE THREAD

**Issue by jaytavares** [anboralabs/intellij-firebase-highlighter#12]
<img width="789" alt="Screen Shot 2020-10-28 at 7 26 23 PM" src="https://user-images.githubusercontent.com/711127/97507386-7de3e780-1953-11eb-9471-6d97f42dcb2c.png">

The rules that use this function run fine in Firebase but intellij-firebase-highlighter detects a problem with the `get` call.

**Comment by dalgarins** [comment]
Thanks for testing, the changes gonna be available for version: 1.1.1
![Screen Shot 2020-10-28 at 10 45 42 PM](https://user-images.githubusercontent.com/8527174/97523102-64e92f80-196f-11eb-8d15-0e59f2790bdd.png)

**Comment by jaytavares** [comment]
<img width="832" alt="Screen Shot 2020-11-02 at 2 12 46 PM" src="https://user-images.githubusercontent.com/711127/97909070-9cf8c580-1d15-11eb-8bef-87f2326a3f2d.png">

It looks like there might be another false positive that cropped up in #13. Now the closing brace of my helper function has the following error: 

> <boolean operator>, FirebaseRulesTokenType.. or FirebaseRulesTokenType.DOT_COMMA expected, got '}'

**Comment by dalgarins** [comment]
@jaytavares every return statement must end with `;`, make the change and let me know if you find a new issue.

**Comment by jaytavares** [comment]
Ah! Of course. 🤦‍♂️
