### ISSUE TITLE
False positive with parantheses in a rule

### ISSUE THREAD

**Issue by akauppi** [anboralabs/intellij-firebase-highlighter#23]
<img width="488" alt="image" src="https://user-images.githubusercontent.com/1297734/101261937-6dd5d980-3743-11eb-83fd-2ff5c5915ecf.png">

That rule is valid, but the plugin reports an error.

WebStorm 2020.3 Build #WS-203.5981.135
plugin 1.1.5-SNAPSHOT

**Comment by dalgarins** [comment]
![Screen Shot 2020-12-13 at 12 48 56 AM](https://user-images.githubusercontent.com/8527174/102004250-012b8380-3cdd-11eb-9097-b523c3d2865c.png)

**Comment by dalgarins** [comment]
Thanks for testing, the issue will be fixed on version: 2.0.0
