### ISSUE TITLE
Syntax check shortcoming... +++

### ISSUE THREAD

**Issue by akauppi** [anboralabs/intellij-firebase-highlighter#24]
First, it's very nice you have brought an IntelliJ plugin for Firebase security rules to existence. Thank You!

The real benefit from such would be in complex rules, highlighting rule syntax problems. Unfortunately, this is where my 2s test already failed:

```
      allow create: if isSignedIn() +++
```

The plugin does not mark the (added) `+++` as a breach of syntax. Surely, it is...

For being able to truly put one's weight on such a plugin, would it be possible to bring Firebase authors in the loop, to help make it more aligned with the real rules language.

**Comment by dalgarins** [comment]
![Screen Shot 2020-12-13 at 12 27 07 AM](https://user-images.githubusercontent.com/8527174/102003956-f4f1f700-3cd9-11eb-9221-34b67e013a5d.png)

**Comment by dalgarins** [comment]
Thanks for testing, issue will be fixed on version: 2.0.0
