### ISSUE TITLE
Block comments not seen as comments

### ISSUE THREAD

**Issue by akauppi** [anboralabs/intellij-firebase-highlighter#25]
![image](https://user-images.githubusercontent.com/1297734/101262064-7da1ed80-3744-11eb-9e01-870905d1caa9.png)

The rules language does treat `/* ... */` as a comment. 

The plugin (1.1.5-SNAPSHOT) does not render it as such.

**Comment by dalgarins** [comment]
![Screen Shot 2020-12-13 at 12 25 37 AM](https://user-images.githubusercontent.com/8527174/102003930-c247fe80-3cd9-11eb-8d49-c7581bca660a.png)

**Comment by dalgarins** [comment]
Thanks for testing, issue will be fixed on version: 2.0.0
