### ISSUE TITLE
False positive for database references

### ISSUE THREAD

**Issue by malliaridis** [anboralabs/intellij-firebase-highlighter#35]
I wrote some time ago a function that is acceptable for firebase rules that looks as follow:
```
function isResourceAuthor() {
  return isSignedIn()
         && resource.data.author == /databases/$(database)/documents/authors/$(request.auth.uid);
}
```
The first slash in the reference after the comparison is recognized as error with the message `<expression> expected, got '/'`.

![Screenshot_1](https://user-images.githubusercontent.com/33470669/104357118-10386800-550d-11eb-85e5-29e593e11e32.jpg)

**Comment by dalgarins** [comment]
<img width="932" alt="Captura de Pantalla 2021-01-23 a la(s) 9 47 40 a  m" src="https://user-images.githubusercontent.com/8527174/105595008-51c4e080-5d61-11eb-8487-53999d38bc9d.png">

Thanks for testing this issue will be fixed on version: 2.2.0
