### ISSUE TITLE
False positive for Map.get()

### ISSUE THREAD

**Issue by bachmanbdc** [anboralabs/intellij-firebase-highlighter#44]
Having an issue with this function:
```
function hasGlobalClaim(claim) {
    return get(/databases/$(database)/documents/Users/$(request.auth.uid)).data.globalClaims.get(claim, false) == true;
}
```

According to the reference [here](https://firebase.google.com/docs/reference/rules/rules.Map) it looks like this should be valid syntax, but it's identified as being incorrect with `IDENTIFIER expected, got 'get'`.

![image](https://user-images.githubusercontent.com/38223357/105896553-f2770280-5fe4-11eb-876c-a0efd772decb.png)

Firestore accepts this and it works as intended.

**Comment by dalgarins** [comment]
<img width="969" alt="Captura de Pantalla 2021-01-28 a la(s) 8 17 27 a  m" src="https://user-images.githubusercontent.com/8527174/106143909-6e865d00-6141-11eb-866a-6ad1c5f4dd6a.png">

@bachmanbdc Thanks for testing, issue will be fixed for version: 2.3.0
