### ISSUE TITLE
Missing "is" operator

### ISSUE THREAD

**Issue by PegasisForever** [anboralabs/intellij-firebase-highlighter#45]
![image](https://user-images.githubusercontent.com/39028532/105955414-3ea55f80-6044-11eb-816e-b9e9006bb137.png)

**Comment by dalgarins** [comment]
<img width="846" alt="Captura de Pantalla 2021-01-28 a la(s) 8 17 01 a  m" src="https://user-images.githubusercontent.com/8527174/106143819-5282bb80-6141-11eb-9f87-93e24af179e0.png">

Thanks for testing, issue will be fixed on version: 2.3.0
