### ISSUE TITLE
Missing "in" operator

### ISSUE THREAD

**Issue by mcarriere** [anboralabs/intellij-firebase-highlighter#5]
Hi, great work on this plugin by the way!

Almost everything is covered in my rules file except the "in" operator on an array.

Ex:
![image](https://user-images.githubusercontent.com/25467653/96043500-0e430800-0e3d-11eb-84d7-e906f7f7bbd8.png)

**Comment by dalgarins** [comment]
Thanks for testing, now I've added "in" operator, this will be available for version: 1.0.2

![Screen Shot 2020-10-14 at 9 24 43 PM](https://user-images.githubusercontent.com/8527174/96070027-fed7b500-0e64-11eb-8048-df1150668fd7.png)
