### ISSUE TITLE
Issue with list indexing syntax

### ISSUE THREAD

**Issue by Karlinator** [anboralabs/intellij-firebase-highlighter#50]
I have the following line: 

    && (get(request.resource.data.participants.removeAll(resource.data.participants)[0]).id == request.auth.uid

Which gets a syntax error like so:

![image](https://user-images.githubusercontent.com/609585/108769698-a4a8d800-7559-11eb-872e-6d37d7d76a49.png)

Even though this is valid syntax. In this case `participants` is a list which I am indexing at position 0.

See: https://firebase.google.com/docs/reference/rules/rules.List

The error is `')', ',' or '.' expected, got '['`.

This also kills the code folding, which seems to not know what's going on because of the error.

Great work though! Always amazed at the breadth of plugins there are out there maintained by some unthanked dev somewhere, so: thank you!

**Comment by dalgarins** [comment]
<img width="985" alt="Captura de Pantalla 2021-03-17 a la(s) 10 26 32 p  m" src="https://user-images.githubusercontent.com/8527174/111569016-dd5e5a80-876f-11eb-9379-ec5e01b3b8cf.png">

Thanks for testing, issue will be fixed on version: 2.5.0,

sorry for late response I was adding code completion feature.
