### ISSUE TITLE
Shows error when path starts with dot

### ISSUE THREAD

**Issue by paslavsky** [anboralabs/intellij-firebase-highlighter#52]
I wrote security rules for Firestore like this:
```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if false;
    }

    match /some-path/{doc} {
      allow write, read: if (request.auth != null);
    }

    match /.some-path/{doc} {
      allow write: if false;
      allow read: if (request.auth != null);
    }
  }
}
```
This is a valid file and it successfully deployed. But my IDE shows two errors:
* <path statement> expected, got '.'
* '/' expected, got 'some-path'

**Comment by dalgarins** [comment]
<img width="459" alt="Captura de Pantalla 2021-03-25 a la(s) 11 07 53 p  m" src="https://user-images.githubusercontent.com/8527174/112575848-21301000-8dbf-11eb-9ad5-42172dc51a18.png">

Thanks for testing issue will be fixed on version: 2.5.1
