### ISSUE TITLE
False Error when using substring 

### ISSUE THREAD

**Issue by paslavsky** [anboralabs/intellij-firebase-highlighter#53]
The following Firestore security rule file:
```
rules_version = '2';
service cloud.firestore {
    match /databases/{database}/documents {
        match /{document=**} {
            allow read, write: if false;
        }

        match /my-collection/{doc} {
            allow read, write: if doc[0:3] == 'ABC';
        }
    }
}
```
shows error `',', <number operator> or ']' expected, got ':'`

**Comment by dalgarins** [comment]
<img width="459" alt="Captura de Pantalla 2021-03-25 a la(s) 11 07 53 p  m" src="https://user-images.githubusercontent.com/8527174/112575808-0bbae600-8dbf-11eb-8316-2d4481f29fd1.png">

Thanks for testing, the issue will be fixed on version: 2.5.1
