### ISSUE TITLE
Array indexing with a variable

### ISSUE THREAD

**Issue by Artelis** [anboralabs/intellij-firebase-highlighter#57]
```
function githubExample(value) {
  return request.resource.data[value];
}
```
The plugin highlights the "value" indexer with: `'[' or number expected, got 'value'`

**Comment by dalgarins** [comment]
<img width="706" alt="Captura de Pantalla 2021-04-12 a la(s) 11 17 01 p  m" src="https://user-images.githubusercontent.com/8527174/114496275-355c7580-9be5-11eb-823e-580bfcfeb0b0.png">

@Artelis thanks for testing, issue will be fixed on version: 2.5.3
