### ISSUE TITLE
Plugin completely not working on Android Studio / macOS Big Sur

### ISSUE THREAD

**Issue by emiliodallatorre** [anboralabs/intellij-firebase-highlighter#58]
This plugin is not usable on Android Studio on macOS Big Sur 11.2.3.
Specifically, it:

- Does not highlights the syntax
- Prevent me from editing `.rules` files (I mean, when I have it installed, I cannot edit anyway my `.rules` files)

The only clue I have that it is installed is that the icon of `.rules` files changes and become the little flame icon like Firebase.

I have not been able to recover any log file which may be useful to resolve this error...

**Comment by dalgarins** [comment]
Which Android studio version are you using?

**Comment by emiliodallatorre** [comment]
Hi,
```
Android Studio 4.1.3
Build #AI-201.8743.12.41.7199119, built on March 11, 2021
Runtime version: 1.8.0_242-release-1644-b3-6915495 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true
Non-Bundled Plugins: mobi.hsz.idea.gitignore, org.intellij.plugins.markdown, org.jetbrains.kotlin, com.jetbrains.darkPurpleTheme, com.developerphil.adbidea, pl.pszklarska.pubversionchecker, Dart, io.flutter, com.localizely.flutter-intl, tanvd.grazi, PythonCore
```

That's all the data I have been able to gather.

**Comment by dalgarins** [comment]
@emiliodallatorre the issue will be fixed on version: 2.5.2

**Comment by dalgarins** [comment]
@emiliodallatorre is the issue fixed for you? let me know if the plugin is working for your mac big sur.

**Comment by emiliodallatorre** [comment]
> @emiliodallatorre is the issue fixed for you? let me know if the plugin is working for your mac big sur.

Hi,
yes: the plugin is now correctly working.

Thank you for the kind attention to this bug, it has been really appreciated.
