### ISSUE TITLE
Lines with only allow write; or allow read; fail

### ISSUE THREAD

**Issue by Gsiete** [anboralabs/intellij-firebase-highlighter#60]
```
    match /items/{item} {
      allow write;
    }
```
Complains saying that `,` or `:` is expected

**Comment by dalgarins** [comment]
<img width="363" alt="Captura de Pantalla 2021-04-22 a la(s) 10 45 40 p  m" src="https://user-images.githubusercontent.com/8527174/115815451-97269780-a3bc-11eb-86dd-f0460f6a4dc9.png">

@Gsiete thanks for testing, issue will be fixed on version: 2.5.5
