### ISSUE TITLE
rejects parentheses around expressions

### ISSUE THREAD

**Issue by Gsiete** [anboralabs/intellij-firebase-highlighter#63]
In this code:
```
    function fieldUnchanged(field) {
      return field in request.resource.data && field in resource.data && resource.data[field] == request.resource.data[field]
        || !(field in request.resource.data) && !(field in resource.data);
    }
```
it rejects the parentheses around the `in` expression in this: `!(field in request.resource.data)`

**Comment by dalgarins** [comment]
<img width="891" alt="Captura de Pantalla 2021-05-01 a la(s) 10 41 37 p  m" src="https://user-images.githubusercontent.com/8527174/116801325-84a01280-aace-11eb-93c2-f298b49f2a46.png">

thanks for testing, issue will be fixed on version: 2.5.6
