### ISSUE TITLE
list type is not recongized

### ISSUE THREAD

**Issue by 0ttik** [anboralabs/intellij-firebase-highlighter#65]
```
rules_version = '2';
service cloud.firestore {
    match /databases/{database}/documents {
        allow read, write: if  request.resource.data.someList is list; // <expression> expected, got 'list'
    }
}
```

**Comment by dalgarins** [comment]
<img width="891" alt="Captura de Pantalla 2021-05-01 a la(s) 10 43 37 p  m" src="https://user-images.githubusercontent.com/8527174/116801340-b1542a00-aace-11eb-8a12-0837a3944681.png">

thanks for testing, issue will be fixed on version: 2.5.6
