### ISSUE TITLE
Security Rules ternary operator not recognized

### ISSUE THREAD

**Issue by akauppi** [anboralabs/intellij-firebase-highlighter#68]
Hi Darwin(?),

I wonder if it's okay to file support requests / bug reports here?  I started evaluating your plugin (2.5.6-SNAPSHOT) today.

# Description

Syntax highlighting does not recognise the ternary operator (? :). 

<img width="415" alt="Näyttökuva 2021-5-18 kello 14 53 47" src="https://user-images.githubusercontent.com/1297734/118647014-8ca7c400-b7e9-11eb-9d59-783c94ee8634.png">

There are also some other, unexplained syntax errors shown for what is a working `.rules` file. Let me know if you want to know about them.

**Comment by dalgarins** [comment]
@akauppi thanks for testing, yes, please, create report all the issues that you found.

**Comment by dalgarins** [comment]
Only add the label feature if it's something new to support.

**Comment by dalgarins** [comment]
Ternary operator is not implemented yet, I'll be working on this.

**Comment by dalgarins** [comment]
<img width="509" alt="Captura de Pantalla 2021-05-27 a la(s) 8 34 00 p  m" src="https://user-images.githubusercontent.com/8527174/119916842-e6676700-bf2a-11eb-9554-6a906dbbe184.png">

thanks for testing, issue will be fixed on version: 2.5.8
