### ISSUE TITLE
Feature request: support spell check for comments 

### ISSUE THREAD

**Issue by erlichmen** [anboralabs/intellij-firebase-highlighter#74]
[Here is](https://stackoverflow.com/questions/12445117/how-to-enable-spellchecking-for-custom-language-plugins-in-idea) some info on how to add spell checker

**Comment by dalgarins** [comment]
<img width="446" alt="Captura de Pantalla 2021-06-11 a la(s) 11 00 59 p  m" src="https://user-images.githubusercontent.com/8527174/121764383-0725e400-cb09-11eb-9fba-eee1b62dc8f1.png">

@erlichmen thanks for testing, feature will be added on version: 2.6.2
