### ISSUE TITLE
Highlight Comments

### ISSUE THREAD

**Issue by jeffreymeng** [anboralabs/intellij-firebase-highlighter#8]
Currently, single-line comments with `//` don't seem to be supported.

<img width="449" alt="2020-10-27_10-09-11" src="https://user-images.githubusercontent.com/15185258/97336701-872e6080-183c-11eb-9b5e-bce06ea531d6.png">

**Comment by dalgarins** [comment]
Thanks for testing, now is possible have comments, this will be able for version: 1.1.0
![Screen Shot 2020-10-27 at 11 31 53 PM](https://user-images.githubusercontent.com/8527174/97391283-e035dd00-18ac-11eb-8b89-7267fa70a9b7.png)
