### ISSUE TITLE
Interpolations incorrectly highlighted as an error

### ISSUE THREAD

**Issue by kirjs** [anboralabs/intellij-firebase-highlighter#85]
**Describe the bug**
Interpolations incorrectly highlighted as an error

**To Reproduce**
```
rules_version = '2';

service cloud.firestore {
  match /databases/{database}/documents {
    match /hotels/{hotelId}/availability/{document=**} {
      allow read, write: if get(/databases/$(database)/documents/hotels/$(hotelId)/users/$(request.auth.uid)).data.write == true;
    }
  }
}

```
**Expected behavior**
This compiles and works in firestore

**Screenshots**
![image](https://user-images.githubusercontent.com/2545357/146690664-d0e4d43e-9ac8-4150-86de-98410f430a85.png)

**Desktop (please complete the following information):**
 - OS: Mac Os
 - Browser n/a

**Comment by dalgarins** [comment]
<img width="1155" alt="Captura de Pantalla 2021-12-20 a la(s) 8 49 53 p m" src="https://user-images.githubusercontent.com/8527174/146857215-d40ae456-a467-4902-bdee-65762c8d74cc.png">

@kirjs thanks for your comments, issue is fixed right now, and it will available on version: 2.7.0
