### ISSUE TITLE
Wrong duplicate definition error for nested functions

### ISSUE THREAD

**Issue by bbrazsilveira** [anboralabs/intellij-firebase-highlighter#87]
**Describe the bug**
Wrong duplicate definition error for nested functions.

**To Reproduce**
1. Create a function named "example()" in a nested match /databases/{database}/documents/collectionA
2. Create a function named "example()" in a nested match /databases/{database}/documents/collectionB
3. See error Duplicate definions with name `example`

**Expected behavior**
The plugin should not search for duplicated functions in sibling matches structures.

**Screenshots**
![image](https://user-images.githubusercontent.com/7516541/149670479-3d0a466f-8e43-484d-802a-e153cdf7ee2c.png)

**Possible solution**
In `src/main/kotlin/co/anbora/labs/firebase/ide/inspections/DuplicateFunctionsInspection.kt`
[DuplicateFunctionsInspection.kt](https://github.com/anboralabs/intellij-firebase-highlighter/blob/master/src/main/kotlin/co/anbora/labs/firebase/ide/inspections/DuplicateFunctionsInspection.kt)

Concat the match path of the function in the key for comparison, at line: 29
`val key = it.identifierExpr?.text + "_" + it.functionParameterList?.functionParameterList?.size`

**Comment by dalgarins** [comment]
@bbrazsilveira let me know if the issue was fixed to you.
