### ISSUE TITLE
Support EAP IDE builds

### ISSUE THREAD

**Issue by niklv** [anboralabs/intellij-firebase-highlighter#88]
Can not use plugin with Webstorm 2022.1 EAP.

**Comment by dalgarins** [comment]
@niklv could you share IDE's log file?

**Comment by niklv** [comment]
@dalgarins there are an error in plugins section: 
![изображение](https://user-images.githubusercontent.com/3831943/158692516-4374879b-d193-4b09-8d9b-739f8bf1e1d3.png)

**Comment by dalgarins** [comment]
thanks for testing, the issue was fixed for version: 2.7.1, soon will be available.

**Comment by dalgarins** [comment]
@niklv the new version is available on the marketplace, let me know if fix works for you.

**Comment by niklv** [comment]
Thank you, issue resolved!
